const translations = {
    en: {
        // نفس الترجمات التي لديك بالضبط لا تغيير
        dashboard: "Dashboard",
        users: "Users",
        drones: "Drones",
        missions: "Missions",
        analytics: "Analytics",
        reports: "Reports",
        services: "Services",
        settings: "Settings",
        overview: "Overview",
        themes: "Themes",
        security: "Security",
        permissions: "Permissions",
        help: "Help",
        logout: "Log Out",

        admin_role: "Admin",
        search_placeholder: "Search missions, drones, or users...",

        total_drones: "Total Drones",
        active_users: "Active Users",
        current_missions: "Current Missions",
        running_projects: "running & completed projects",
        completion_rate: "Completion rate this month",
        missions_status: "Missions Status",
        fleet_map: "Fleet Live Map",
        running_completed: "Running & completed projects tracking",
        drones_active: "12 Drones Active Now",
        this_year: "This Year",

        live_intel: "Live Intelligence",
        field_health: "Field Health Score",
        ndvi_index: "NDVI Index",
        anomaly: "Anomaly",
        none: "None",
        alerts: "Alerts",
        reports_count: "Reports",
        ai_analyzing: "Analyzing soil moisture...",

        active: "Active",
        maintenance: "Maintenance",
        returning: "Returning",
        critical: "Critical",
        drone_model: "Model",
        altitude: "Altitude",
        battery: "Battery",

        users_management: "Users Management",
        users_desc: "Manage system users, roles, permissions and drone access",
        add_new_user: "Add New User",
        total_users: "Total Users",
        online_now: "Online Now",
        admins: "Admins",
        suspended: "Suspended",
        system_users: "System Users List",
        users_list_desc: "All registered users with assigned drones & services",
        search_users: "Search by ID, name, email or drone...",
        user_id: "User ID",
        full_name: "Full Name",
        email: "Email",
        service: "Service",
        status: "Status",
        assigned_drone: "Assigned Drone",
        payment: "Payment",
        actions: "Actions",
        service_agriculture: "Agriculture",
        service_security: "Security",
        service_mapping: "Mapping",
        status_active: "Active",
        status_mission: "On Mission",
        status_suspended: "Suspended",
        payment_paid: "Paid",
        payment_pending: "Pending",
        payment_overdue: "Overdue",
        showing_users: "Showing",
        of_users: "of",

        fleet_management: "Drones Fleet Management",
        fleet_desc: "Manage all drones, technical specs, battery status and service assignments",
        add_drone: "Register New Drone",
        active_in_flight: "Active In Flight",
        in_maintenance: "Under Maintenance",
        reserved: "Reserved",
        drones_list: "Full Drones List",
        drones_list_desc: "Complete fleet database with full technical information",
        search_drone: "Search by ID, model or serial...",
        drone_id: "Drone ID",
        manufacture_date: "Manufacture Date",
        specs: "Specifications",
        assigned_service: "Assigned Service",

        data_analytics: "Advanced Analytics",
        analytics_desc: "Deep AI-driven insights for crop monitoring and drone performance metrics",
        export_report: "Export PDF Report",
        crop_health_index: "Crop Health Index (NDVI)",
        fleet_efficiency: "Fleet Operational Efficiency",
        ai_accuracy: "AI Diagnosis Accuracy",
        area_covered: "Total Area Covered",
        detected_diseases: "Detected Plant Diseases",
        active_alerts: "Active alerts requiring attention",

        mission_control: "Mission Control Center",
        mission_desc: "Real-time flight monitoring and tactical mission planning",
        create_mission: "New Mission",
        in_progress: "In Progress",
        upcoming_missions: "Upcoming Missions",

        report_title: "Service Administration",
        report_desc: "Global monitoring of user reports and AI diagnostic accuracy",
        select_client: "Select Client",
        all_users: "All Registered Users",
        btn_export: "Export PDF",
        stat_active_clients: "Active Clients",
        stat_global_diagnostics: "Global Diagnostics",
        stat_ai_confidence: "AI Confidence Avg.",
        stat_critical: "Critical Reports",
        today: "Today",
        high: "High",
        action_req: "Action Req.",
        table_title: "Service-Wide Diagnostic Logs",
        table_client: "Client / User",
        table_crop: "Target Crop",
        table_result: "AI Result",
        table_confidence: "Confidence",
        table_action: "Review",
        late_blight: "Late Blight",
        chart_title: "Global Disease Spread",
        top_clients: "Top Healthy Clients",
        health_status: "98% Health",
        settings: "Settings",
        settings_desc: "Manage your account, security, and drone fleet preferences.",
        profile: "Profile",
        security: "Security",
        permissions: "Permissions",
        notifications: "Notifications",
        full_name: "Full Name",
        email: "Email Address",
        change_password: "Change Password",
        btn_save: "Save Changes",
        btn_discard: "Discard",
        security_settings: "Security Settings",
        security_desc: "Manage your password, 2FA, and session security.",
        current_password: "Current Password",
        new_password: "New Password",
        confirm_password: "Confirm New Password",
        two_factor: "Two-Factor Authentication (2FA)",
        two_factor_desc: "Add an extra layer of security to your account.",
        active_sessions: "Active Sessions",
        logout_all: "Log out from all devices",
        permissions_settings: "Role & Permissions",
        permissions_desc: "Control your access level and drone fleet authority.",
        your_role: "Your Current Role",
        drone_control: "Drone Flight Control",
        data_access: "Sensitive Data Access",
        fleet_management_perm: "Fleet Management Authority",

        notifications_settings: "Notification Preferences",
        notifications_desc: "Choose how you want to receive alerts and mission updates.",
        email_notif: "Email Notifications",
        push_notif: "Push Notifications",
        mission_alerts: "Mission Status Alerts",
        fleet_updates: "Fleet Maintenance Reminders",
        security_alerts: "Security & Login Alerts",
        help_desc: "Everything you need to know about Skyline LAND platform and drone operations.",
        search_help: "Search for guides, tutorials...",
        faq_drone_setup: "Drone Setup Guide",
        faq_drone_setup_desc: "Learn how to calibrate your drone sensors and connect to the AirSim environment.",
        faq_analysis: "AI Crop Analysis",
        faq_analysis_desc: "Understanding NDVI indices and how our AI detects plant diseases in real-time.",
        still_need_help: "Still need help?",
        contact_desc: "Our technical team is available 24/7 for mission-critical support.",
        contact_us: "Contact Support",

        // Modals Additions
        new_user_subtitle: "System Registration",
        enter_full_name: "Full Name",
        enter_email: "Email Address",
        cancel: "Cancel",
        save_user: "Save User Account",
        surveillance: "Surveillance",
        delivery: "Delivery",
        mapping: "Mapping",
        password: "Password",
        add_new_drone: "Add New Drone",
        drone_system_subtitle: "Drone Command System",
        enter_drone_name: "Drone Name / Model",
        specifications: "Specifications (e.g., 4K Camera, 50km range)",
        save_drone: "Save Drone",

        mission_system_subtitle: "Tactical Operations Command",
        enter_mission_name: "Mission Name / ID",
        target_area: "Target Area / Coordinates",
        select_drone: "Select Drone",
        mission_type: "Mission Type",
        scheduled_time: "Scheduled Time",
        save_mission: "Start Mission",
        all_missions: "All Missions",
        hectares: "Hectares",

        add_new_service: "Add New Service",
        service_modal_desc: "Setup a new specialized drone operation package.",
        service_name: "Service Name",
        enter_service_name: "New Service...",
        service_category: "Category",
        service_price: "Price ($/Month)",
        description: "Description",

        skyline_hub: "Skyline <span class='text-cyan-400'>Hub</span>",
        services_desc: "Select your specialized drone sector to explore tailored solutions.",
        service_agriculture: "Smart Agriculture",
        agri_sub: "Monitoring, Spraying & Mapping",
        service_security: "Security & Patrol",
        sec_sub: "Forests, Schools & Home Guard",
        service_airgames: "Sky Arts & Events",
        air_sub: "Light Shows & Celebration Displays",

        select_new_cat: "-- Select New Sector --",
        cat_delivery: "Logistics & Delivery",
        cat_inspection: "Industrial Inspection",
        cat_cinema: "Cinematography",
        cat_survey: "Topographical Survey",
        cat_other: "Other (Custom)",
        save_service: "Save Service",
        diagnosis:       "Diagnosis",
diagnosis_title: "AI Image Diagnosis",
drop_title:      "Drop your image here",
drop_sub:        "or browse to upload",
browse:          "browse",
analyze_btn:     "Analyze Image",
diagnosis_result:"Diagnosis Result",
ai_powered:      "AI POWERED",
file_name:       "File name",
file_size:       "File size",
analyzed_at:     "Analyzed at",
ai_analysis:     "AI Analysis",
confidence:      "Confidence",
back:            "Back",

        switch_lang: "العربية"
    },
    ar: {
        dashboard: "لوحة التحكم",
        users: "المستخدمين",
        drones: "الطائرات",
        missions: "المهام",
        analytics: "التحليلات",
        reports: "التقارير",
        services: "الخدمات",
        settings: "الإعدادات",
        overview: "نظرة عامة",
        themes: "المظاهر",
        security: "الأمان",
        permissions: "الصلاحيات",
        help: "المساعدة",
        logout: "تسجيل الخروج",

        admin_role: "مدير النظام",
        search_placeholder: "ابحث عن المهام، الدرونات، أو المستخدمين...",

        total_drones: "إجمالي الدرونات",
        active_users: "المستخدمين النشطين",
        current_missions: "المهام الحالية",
        running_projects: "المشاريع الجارية والمكتملة",
        completion_rate: "معدل الإنجاز هذا الشهر",
        missions_status: "حالة المهام",
        fleet_map: "خريطة الأسطول المباشرة",
        running_completed: "تتبع المشاريع الجارية والمكتملة",
        drones_active: "12 طائرة نشطة الآن",
        this_year: "هذا العام",

        live_intel: "الذكاء الاصطناعي المباشر",
        field_health: "مؤشر صحة الحقل",
        ndvi_index: "مؤشر الغطاء النباتي (NDVI)",
        anomaly: "حالات شاذة",
        none: "لا يوجد",
        alerts: "التنبيهات",
        reports_count: "التقارير",
        ai_analyzing: "تحليل رطوبة التربة...",

        active: "نشط",
        maintenance: "صيانة",
        returning: "قيد العودة",
        critical: "حرج",
        drone_model: "الطراز",
        altitude: "الارتفاع",
        battery: "البطارية",

        users_management: "إدارة المستخدمين",
        users_desc: "إدارة مستخدمي النظام، الأدوار، الصلاحيات والوصول للطائرات",
        add_new_user: "إضافة مستخدم جديد",
        total_users: "إجمالي المستخدمين",
        online_now: "متصلون الآن",
        admins: "المشرفين",
        suspended: "محظورون",
        system_users: "قائمة مستخدمي النظام",
        users_list_desc: "جميع المستخدمين المسجلين مع الطائرات والخدمات المخصصة لهم",
        search_users: "ابحث بالرقم، الاسم، البريد او رقم الطائرة...",
        user_id: "رقم المستخدم",
        full_name: "الاسم الكامل",
        email: "البريد الإلكتروني",
        service: "الخدمة",
        status: "الحالة",
        assigned_drone: "الطائرة المخصصة",
        payment: "حالة الدفع",
        actions: "العمليات",
        service_agriculture: "زراعة",
        service_security: "أمن ومراقبة",
        service_mapping: "خرائط ومسح",
        status_active: "نشط",
        status_mission: "في مهمة",
        status_suspended: "موقف",
        payment_paid: "مدفوع",
        payment_pending: "قيد الانتظار",
        payment_overdue: "متأخر",
        showing_users: "عرض",
        of_users: "من إجمالي",

        fleet_management: "إدارة أسطول الطائرات",
        fleet_desc: "إدارة جميع الدرونات، المواصفات التقنية، حالة البطارية والخدمات المخصصة",
        add_drone: "تسجيل طائرة جديدة",
        active_in_flight: "نشطة في الجو",
        in_maintenance: "تحت الصيانة",
        reserved: "محجوزة",
        drones_list: "قائمة كامل الأسطول",
        drones_list_desc: "قاعدة بيانات كاملة لجميع الطائرات مع المعلومات التقنية",
        search_drone: "ابحث بالرقم، الطراز او الرقم التسلسلي...",
        drone_id: "رقم الطائرة",
        manufacture_date: "تاريخ الصنع",
        specs: "المواصفات",
        assigned_service: "الخدمة المخصصة",

        data_analytics: "التحليلات المتقدمة",
        analytics_desc: "رؤى عميقة مدعومة بالذكاء الاصطناعي لمراقبة المحاصيل ومقاييس أداء الدرونات",
        export_report: "تصدير تقرير PDF",
        crop_health_index: "مؤشر صحة المحاصيل (NDVI)",
        fleet_efficiency: "كفاءة تشغيل الأسطول",
        ai_accuracy: "دقة تشخيص الذكاء الاصطناعي",
        area_covered: "إجمالي المساحة المغطاة",
        detected_diseases: "أمراض النبات المكتشفة",
        active_alerts: "تنبيهات نشطة تتطلب اهتماماً",

        mission_control: "مركز التحكم في المهام",
        mission_desc: "مراقبة الطيران في الوقت الفعلي وتخطيط المهام التكتيكية",
        create_mission: "مهمة جديدة",
        in_progress: "قيد التنفيذ",
        upcoming_missions: "المهام القادمة",

        report_title: "إدارة الخدمات",
        report_desc: "المراقبة العامة لتقارير المستخدمين ودقة تشخيص الذكاء الاصطناعي",
        select_client: "اختر العميل",
        all_users: "جميع المستخدمين المسجلين",
        btn_export: "تصدير PDF",
        stat_active_clients: "العملاء النشطون",
        stat_global_diagnostics: "التشخيصات العامة",
        stat_ai_confidence: "متوسط ثقة الذكاء الاصطناعي",
        stat_critical: "تقارير حرجة",
        today: "اليوم",
        high: "مرتفع",
        action_req: "مطلوب إجراء",
        table_title: "سجلات التشخيص على مستوى الخدمة",
        table_client: "العميل / المستخدم",
        table_crop: "المحصول المستهدف",
        table_result: "نتيجة الذكاء الاصطناعي",
        table_confidence: "نسبة الثقة",
        table_action: "مراجعة",
        late_blight: "لفحة متأخرة",
        chart_title: "انتشار الأمراض عالمياً",
        top_clients: "أكثر العملاء صحة",
        health_status: "صحة بنسبة 98%",
        settings: "الإعدادات",
        settings_desc: "إدارة حسابك، الأمان، وتفضيلات أسطول الطائرات بدون طيار.",
        profile: "الملف الشخصي",
        security: "الأمان",
        permissions: "الصلاحيات",
        notifications: "الإشعارات",
        full_name: "الاسم الكامل",
        email: "البريد الإلكتروني",
        change_password: "تغيير كلمة المرور",
        btn_save: "حفظ التغييرات",
        btn_discard: "تجاهل",
        // داخل ar: { ... }
        security_settings: "إعدادات الأمان",
        security_desc: "إدارة كلمة المرور، التحقق بخطوتين، وأمان الجلسات.",
        current_password: "كلمة المرور الحالية",
        new_password: "كلمة المرور الجديدة",
        confirm_password: "تأكيد كلمة المرور الجديدة",
        two_factor: "المصادقة الثنائية (2FA)",
        two_factor_desc: "إضافة طبقة حماية إضافية لحسابك.",
        active_sessions: "الجلسات النشطة",
        logout_all: "تسجيل الخروج من جميع الأجهزة",

        permissions_settings: "الأدوار والصلاحيات",
        permissions_desc: "التحكم في مستوى وصولك وصلاحياتك في أسطول الطائرات.",
        your_role: "دورك الحالي",
        drone_control: "التحكم في طيران الدرون",
        data_access: "الوصول للبيانات الحساسة",
        fleet_management_perm: "صلاحية إدارة الأسطول",

        notifications_settings: "تفضيلات الإشعارات",
        notifications_desc: "اختر كيف ترغب في تلقي التنبيهات وتحديثات المهام.",
        email_notif: "إشعارات البريد الإلكتروني",
        push_notif: "إشعارات المتصفح",
        mission_alerts: "تنبيهات حالة المهام",
        fleet_updates: "تذكيرات صيانة الأسطول",
        security_alerts: "تنبيهات الأمان وتسجيل الدخول",
        help_desc: "كل ما تحتاج لمعرفته حول منصة Skyline LAND وعمليات الطائرات بدون طيار.",
        search_help: "ابحث عن الأدلة، الشروحات...",
        faq_drone_setup: "دليل إعداد الطائرة",
        faq_drone_setup_desc: "تعلم كيفية معايرة مستشعرات الطائرة والاتصال ببيئة محاكاة AirSim.",
        faq_analysis: "تحليل المحاصيل بالذكاء الاصطناعي",
        faq_analysis_desc: "فهم مؤشرات NDVI وكيفية اكتشاف الذكاء الاصطناعي لأمراض النبات في الوقت الفعلي.",
        still_need_help: "هل لا تزال بحاجة للمساعدة؟",
        contact_desc: "فريقنا الفني متاح على مدار الساعة للدعم في المهام الحرجة.",
        contact_us: "اتصل بالدعم الفني",

        // Modals Additions
        new_user_subtitle: "تسجيل في النظام",
        enter_full_name: "الاسم الكامل",
        enter_email: "البريد الإلكتروني",
        cancel: "إلغاء",
        save_user: "حفظ مستخدم جديد",
        surveillance: "استطلاع ومراقبة",
        delivery: "توصيل إمدادات",
        mapping: "مسح وخرائط",
        password: "كلمة المرور",
        add_new_drone: "إضافة طائرة جديدة",
        drone_system_subtitle: "نظام قيادة الطائرات",
        enter_drone_name: "اسم الطائرة أو الموديل",
        specifications: "المواصفات (مثال: كاميرا 4K، مدى 50 كم)",
        save_drone: "حفظ الطائرة",

        mission_system_subtitle: "مركز العمليات التكتيكية",
        enter_mission_name: "اسم المهمة أو المعرف",
        target_area: "المنطقة المستهدفة أو الإحداثيات",
        select_drone: "اختيار الطائرة",
        mission_type: "نوع المهمة",
        scheduled_time: "وقت التنفيذ المجدول",
        save_mission: "بدء المهمة",
        all_missions: "جميع المهام",
        hectares: "هكتار",

        add_new_service: "إضافة خدمة جديدة",
        service_modal_desc: "إعداد باقة عمليات طيران مسير متخصصة.",
        service_name: "اسم الخدمة",
        enter_service_name: "الخدمة الجديدة...",
        service_category: "الفئة",
        service_price: "السعر ($/شهر)",
        description: "الوصف التوضيحي",

        skyline_hub: "مركز <span class='text-cyan-400'>skyline</span>",
        services_desc: "اختر قطاع طائرات الدرون المتخصص بك لاستكشاف الحلول المبتكرة.",
        service_agriculture: "الزراعة الذكية",
        agri_sub: "مراقبة المحاصيل، رش المبيدات ورسم الخرائط",
        service_security: "الأمن والدوريات",
        sec_sub: "حراسة الغابات، المدارس، وحماية المنشآت",
        service_airgames: "فنون السماء والفعاليات",
        air_sub: "عروض الأضواء وطائرات الدرون للاحتفالات",

        select_new_cat: "-- اختر قطاعاً جديداً --",
        cat_delivery: "خدمات التوصيل واللوجستيات",
        cat_inspection: "الفحص الصناعي والبنية التحتية",
        cat_cinema: "التصوير السينمائي",
        cat_survey: "المسح الطبوغرافي",
        cat_other: "أخرى (مخصص)",
        save_service: "حفظ الخدمة",
        diagnosis:       "التشخيص",
diagnosis_title: "تشخيص الصور بالذكاء الاصطناعي",
drop_title:      "أسقط صورتك هنا",
drop_sub:        "أو تصفّح للرفع",
browse:          "تصفّح",
analyze_btn:     "تحليل الصورة",
diagnosis_result:"نتيجة التشخيص",
ai_powered:      "بالذكاء الاصطناعي",
file_name:       "اسم الملف",
file_size:       "حجم الملف",
analyzed_at:     "وقت التحليل",
ai_analysis:     "التحليل الذكي",
confidence:      "مستوى الثقة",
back:            "رجوع",

        switch_lang: "English"
    }
};

// دالة تحديث النصوص في الصفحة
function updatePageText(lang) {
    document.querySelectorAll('[data-i18n], [data-key], [data-t]').forEach(el => {
        const key = el.getAttribute('data-i18n') || el.getAttribute('data-key') || el.getAttribute('data-t');
        if (translations[lang] && translations[lang][key]) {
            const icon = el.querySelector('i, svg');
            if (icon) {
                const iconClone = icon.cloneNode(true);
                el.innerHTML = ' ' + translations[lang][key]; // نضع النص كـ HTML
                el.prepend(iconClone); // نضع الأيقونة قبله
            } else {
                el.innerHTML = translations[lang][key]; // نضع النص كـ HTML ليظهر التنسيق
            }
        }
    });

    // تحديث الـ Placeholders
    document.querySelectorAll('[data-i18n-placeholder], [data-key-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder') || el.getAttribute('data-key-placeholder');
        if (translations[lang][key]) el.placeholder = translations[lang][key];
    });
}

// الدالة الرئيسية (المدمجة)
function applyLanguage(lang) {
    // 1. إعدادات الصفحة الأساسية
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.body.style.fontFamily = lang === 'ar' ? "'Tajawal', sans-serif" : "'Inter', sans-serif";

    // 2. حفظ الاختيار وتحديث النصوص
    localStorage.setItem('skyline_lang', lang);
    updatePageText(lang);

    // 3. إعادة رسم الأيقونات
    if (window.lucide) {
        setTimeout(() => lucide.createIcons(), 50);
    }

    // 4. ✅ تشغيل الرسم البياني (إذا كان موجوداً في الصفحة)
    if (typeof initAdminCharts === 'function') {
        initAdminCharts();
    }
}

function toggleLanguage() {
    const current = localStorage.getItem('skyline_lang') || 'en';
    applyLanguage(current === 'en' ? 'ar' : 'en');
}

// التشغيل عند تحميل الصفحة
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('skyline_lang') || 'en';
    applyLanguage(savedLang);
});